# Generated by Django 2.1.7 on 2019-03-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('coliform_bacteria', models.FloatField(blank=True, null=True, verbose_name='Coliform Bacteria')),
                ('nitrate', models.FloatField(blank=True, null=True, verbose_name='Nitrate')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('sodium', models.FloatField(blank=True, null=True, verbose_name='Sodium')),
                ('chloride', models.FloatField(blank=True, null=True, verbose_name='Chloride')),
                ('fluride', models.FloatField(blank=True, null=True, verbose_name='Fluride')),
                ('sulphate', models.FloatField(blank=True, null=True, verbose_name='Sulphate')),
                ('iron', models.FloatField(blank=True, null=True, verbose_name='Iron')),
            ],
            options={
                'verbose_name': 'Water Parameter',
                'verbose_name_plural': 'Water Parameter List',
            },
        ),
    ]
